using UnityEngine;

public class BackgroundManager : MonoBehaviour
{
    //ï¿½ï¿½ ï¿½è¿­ Å©ï¿½ï¿½ ï¿½Þ´ï¿½ ï¿½ï¿½
    private int floorCount;

    [SerializeField] //ï¿½ï¿½ï¿?ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ® 
    private GameObject[] backgroundGameObject;
    //ï¿½ï¿½ ï¿½è¿­ Å©ï¿½ï¿½ ï¿½Þ´ï¿½ ï¿½ï¿½
    private int backgroundGameObjectCount;

    //ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½Ã°ï¿½
    private float nowTime;
    //ï¿½ï¿½ï¿½ï¿½ ï¿½ï¿½ï¿½ï¿½ï¿½Ö´ï¿½ ï¿½ï¿½ï¿?ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ®
    private int nowActiveBackgroundObject;

    private Background background;
    private GameManager gameManager;
    private Tower tower;
    private int idx = 0;
    private void Start()
    {
        nowTime = 0f;
        nowActiveBackgroundObject = 0;
        backgroundGameObjectCount = backgroundGameObject.Length;
        Instantiate(backgroundGameObject[0], this.gameObject.transform);
        background = GetComponent<Background>();
        gameManager = FindObjectOfType<GameManager>();
        tower = FindObjectOfType<Tower>();
    }

    private void Update()
    {
        //nowTime += Time.deltaTime;

        if (backgroundGameObjectCount != nowActiveBackgroundObject + 1)
        {
            if (tower.height >= gameManager.stageHeight[idx])
            {
                idx++;
                nowActiveBackgroundObject++;
                nowTime = 0f;
                Instantiate(backgroundGameObject[nowActiveBackgroundObject], this.gameObject.transform);
                this.gameObject.transform.GetChild(nowActiveBackgroundObject - 1).gameObject.SetActive(false);
            }
        }
    }
}
